

CREATE TABLE SQL_CE_OPPORTUNITYPOINTSDISCR (
	OPPORTUNITYPOINTSDISCNM VARCHAR,
	INSERTEDBY VARCHAR,
	RECORDINSERTDT TIMESTAMP(6),
	RECORDUPDTDT TIMESTAMP(6),
	UPDTDBY VARCHAR,
	OPPORTUNITYPOINTSDISCRCD VARCHAR,
	CONSTRAINT OPPORTUNITYPOINTSDISCR_PK PRIMARY KEY(OPPORTUNITYPOINTSDISCRCD)
);

CREATE TABLE SQL_CE_DERIVEDFACT (
	DERIVEDFACTTRACKINGID BIGINT,
	DERIVEDFACTTYPEID BIGINT,
	INSERTEDBY VARCHAR,
	RECORDINSERTDT TIMESTAMP(6),
	RECORDUPDTDT TIMESTAMP(6),
	UPDTDBY VARCHAR,
	DERIVEDFACTID BIGINT,
	CONSTRAINT DERIVEDFACT_PK PRIMARY KEY(DERIVEDFACTID)
);

CREATE TABLE SQL_CE_RECOMMENDATIONTEXT (
	RECOMMENDATIONTEXTID BIGINT,
	RECOMMENDATIONID BIGINT,
	LANGUAGECD CHAR(2),
	RECOMMENDATIONTEXTTYPE VARCHAR,
	MESSAGETYPE CHAR(3),
	RECOMMENDATIONTITLE VARCHAR,
	RECOMMENDATIONTEXT VARCHAR,
	RECORDINSERTDT TIMESTAMP(6),
	RECORDUPDATEDT TIMESTAMP(6),
	INSERTEDBY VARCHAR,
	UPDATEDBY VARCHAR,
	DEFAULTIN CHAR(1)
);

CREATE TABLE SQL_CE_CLINICAL_CONDITION (
	CLINICAL_CONDITION_NAM VARCHAR,
	INSERTED_BY VARCHAR,
	REC_INSERT_DATE DATE,
	REC_UPD_DATE DATE,
	UPDATED_BY VARCHAR,
	CLINICALCONDITIONCLASSCD BIGINT,
	CLINICALCONDITIONTYPECD VARCHAR,
	CLINICALCONDITIONABBREV VARCHAR,
	CLINICAL_CONDITION_COD BIGINT,
	CONSTRAINT CLINICAL_CONDITION_PK PRIMARY KEY(CLINICAL_CONDITION_COD)
);

CREATE TABLE SQL_CE_PRODUCTOPPORTUNITYPOINTS (
	OPPORTUNITYPOINTSDISCCD VARCHAR,
	EFFECTIVESTARTDT DATE,
	OPPORTUNITYPOINTSNBR BIGINT,
	EFFECTIVEENDDT DATE,
	DERIVEDFACTPRODUCTUSAGEID BIGINT,
	INSERTEDBY VARCHAR,
	RECORDINSERTDT TIMESTAMP(6),
	RECORDUPDTDT TIMESTAMP(6),
	UPDTDBY VARCHAR
);

CREATE TABLE SQL_CE_MEDICALFINDING (
	MEDICALFINDINGID BIGINT,
	MEDICALFINDINGTYPECD VARCHAR,
	MEDICALFINDINGNM VARCHAR,
	SEVERITYLEVELCD VARCHAR,
	IMPACTABLEFLG CHAR(1),
	CLINICAL_CONDITION_COD BIGINT,
	INSERTEDBY VARCHAR,
	RECORDINSERTDT TIMESTAMP(6),
	RECORDUPDTDT TIMESTAMP(6),
	UPDTDBY VARCHAR,
	ACTIVEFLG CHAR(1),
	OPPORTUNITYPOINTSDISCRCD VARCHAR
);

CREATE TABLE SQL_CE_DERIVEDFACTPRODUCTUSAGE (
	DERIVEDFACTID BIGINT,
	PRODUCTMNEMONICCD VARCHAR,
	INSERTEDBY VARCHAR,
	RECORDINSERTDT TIMESTAMP(6),
	RECORDUPDTDT TIMESTAMP(6),
	UPDTDBY VARCHAR,
	DERIVEDFACTPRODUCTUSAGEID BIGINT,
	CONSTRAINT DERIVEDFACTPRODUCTUSAGE_PK PRIMARY KEY(DERIVEDFACTPRODUCTUSAGEID)
);

CREATE TABLE SQL_CE_PRODUCTFINDINGTYPE (
	PRODUCTFINDINGTYPECD VARCHAR,
	PRODUCTFINDINGTYPEDESC VARCHAR,
	INSERTEDBY VARCHAR,
	RECORDINSERTDT TIMESTAMP(6),
	RECORDUPDTDT TIMESTAMP(6),
	UPDTDBY VARCHAR
);

CREATE TABLE SQL_CE_RECOMMENDATION (
	RECOMMENDATIONSKEY BIGINT,
	RECOMMENDATIONID BIGINT,
	RECOMMENDATIONCODE VARCHAR,
	RECOMMENDATIONDESC VARCHAR,
	RECOMMENDATIONTYPE VARCHAR,
	CCTYPE VARCHAR,
	CLINICALREVIEWTYPE VARCHAR,
	AGERANGEID BIGINT,
	ACTIONCODE VARCHAR,
	THERAPEUTICCLASS VARCHAR,
	MDCCODE VARCHAR,
	MCCCODE VARCHAR,
	PRIVACYCATEGORY VARCHAR,
	INTERVENTION VARCHAR,
	RECOMMENDATIONFAMILYID BIGINT,
	RECOMMENDPRECEDENCEGROUPID BIGINT,
	INBOUNDCOMMUNICATIONROUTE VARCHAR,
	SEVERITY VARCHAR,
	PRIMARYDIAGNOSIS VARCHAR,
	SECONDARYDIAGNOSIS VARCHAR,
	ADVERSEEVENT VARCHAR,
	ICMCONDITIONID BIGINT,
	WELLNESSFLAG CHAR(1),
	VBFELIGIBLEFLAG CHAR(1),
	COMMUNICATIONRANKING BIGINT,
	PRECEDENCERANKING BIGINT,
	PATIENTDERIVEDFLAG CHAR(1),
	LABREQUIREDFLAG CHAR(1),
	UTILIZATIONTEXTAVAILABLEF CHAR(1),
	SENSITIVEMESSAGEFLAG CHAR(1),
	HIGHIMPACTFLAG CHAR(1),
	ICMLETTERFLAG CHAR(1),
	REQCLINICIANCLOSINGFLAG CHAR(1),
	OPSIMPELMENTATIONPHASE BIGINT,
	SEASONALFLAG CHAR(1),
	SEASONALSTARTDT DATE,
	SEASONALENDDT DATE,
	EFFECTIVESTARTDT DATE,
	EFFECTIVEENDDT DATE,
	RECORDINSERTDT TIMESTAMP(6),
	RECORDUPDTDT TIMESTAMP(6),
	INSERTEDBY VARCHAR,
	UPDTDBY VARCHAR,
	STANDARDRUNFLAG CHAR(1),
	INTERVENTIONFEEDBACKFAMILYID BIGINT,
	CONDITIONFEEDBACKFAMILYID BIGINT,
	ASHWELLNESSELIGIBILITYFLAG CHAR(1),
	HEALTHADVOCACYELIGIBILITYFLAG CHAR(1)
);

CREATE TABLE SQL_CE_PRODUCTFINDING (
	PRODUCTFINDINGID BIGINT,
	PRODUCTFINDINGNM VARCHAR,
	SEVERITYLEVELCD VARCHAR,
	PRODUCTFINDINGTYPECD VARCHAR,
	PRODUCTMNEMONICCD VARCHAR,
	SUBPRODUCTMNEMONICCD VARCHAR,
	INSERTEDBY VARCHAR,
	RECORDINSERTDT TIMESTAMP(6),
	RECORDUPDTDT TIMESTAMP(6),
	UPDTDBY VARCHAR
);

CREATE TABLE SQL_CE_MEDICALFINDINGTYPE (
	MEDICALFINDINGTYPEDESC VARCHAR,
	INSERTEDBY VARCHAR,
	RECORDINSERTDT TIMESTAMP(6),
	RECORDUPDTDT TIMESTAMP(6),
	UPDTDBY VARCHAR,
	HEALTHSTATEAPPLICABLEFLAG CHAR(1),
	MEDICALFINDINGTYPECD VARCHAR,
	CONSTRAINT MEDICALFINDINGTYPE_PK PRIMARY KEY(MEDICALFINDINGTYPECD)
);
