CREATE TABLE SQL_CE_MEDICALFINDINGTYPE(
  MEDICALFINDINGTYPECD VARCHAR(12),
  MEDICALFINDINGTYPEDESC VARCHAR(255),
  INSERTEDBY VARCHAR(30),
  RECORDINSERTDT TIMESTAMP(6),
  RECORDUPDTDT TIMESTAMP(6),
  UPDTDBY VARCHAR(30),
  HEALTHSTATEAPPLICABLEFLAG CHAR(1),
  CONSTRAINT MEDICALFINDINGTYPE_PK PRIMARY KEY (MEDICALFINDINGTYPECD)
 );

CREATE TABLE SQL_CE_PRODUCTFINDINGTYPE (
  PRODUCTFINDINGTYPECD VARCHAR(12),
  PRODUCTFINDINGTYPEDESC VARCHAR(255),
  INSERTEDBY VARCHAR2(30),
  RECORDINSERTDT TIMESTAMP(6),
  RECORDUPDTDT TIMESTAMP(6),
  UPDTDBY VARCHAR2(30),
  CONSTRAINT PRODUCTFINDINGTYPE_PK PRIMARY KEY (PRODUCTFINDINGTYPECD)
 );

CREATE TABLE SQL_CE_DERIVEDFACT (
  DERIVEDFACTID BIGINT,
  DERIVEDFACTTRACKINGID BIGINT,
  DERIVEDFACTTYPEID VARCHAR(30),
  INSERTEDBY VARCHAR(30),
  RECORDINSERTDT TIMESTAMP(6),
  RECORDUPDTDT TIMESTAMP(6),
  UPDTDBY VARCHAR(30),
  CONSTRAINT DERIVEDFACT_PK PRIMARY KEY (DERIVEDFACTID)
 );

CREATE TABLE SQL_CE_RECOMMENDATION (
  RECOMMENDATIONSKEY BIGINT,
  RECOMMENDATIONID BIGINT,
  RECOMMENDATIONCODE VARCHAR(200),
  RECOMMENDATIONDESC VARCHAR(4000),
  RECOMMENDATIONTYPE VARCHAR(20),
  CCTYPE VARCHAR(50),
  CLINICALREVIEWTYPE VARCHAR(20) ,
  AGERANGEID BIGINT,
  ACTIONCODE VARCHAR(200),
  THERAPEUTICCLASS VARCHAR(300),
  MDCCODE VARCHAR(20),
  MCCCODE VARCHAR(50),
  PRIVACYCATEGORY VARCHAR(20) ,
  INTERVENTION VARCHAR(200),
  RECOMMENDATIONFAMILYID BIGINT,
  RECOMMENDPRECE_ENCE_ROUPID BIGINT,
  INBOUNDCOMMUNICATIONROUTE VARCHAR(15),
  SEVERITY VARCHAR(2),
  PRIMARYDIAGNOSIS VARCHAR(300),
  SECONDARYDIAGNOSIS VARCHAR(300),
  ADVERSEEVENT VARCHAR(300),
  ICMCONDITIONID BIGINT,
  WELLNESSFLAG CHAR(1),
  VBFELIGIBLEFLAG CHAR(1),
  COMMUNICATIONRANKING BIGINT,
  PRECE_ENCE_ANKING BIGINT,
  PATIENTDERIVEDFLAG CHAR(1),
  LABREQUIREDFLAG CHAR(1),
  UTILIZATIONTEXTAVAILABLEF CHAR(1),
  SENSITIVEMESSAGEFLAG CHAR(1),
  HIGHIMPACTFLAG CHAR(1),
  ICMLETTERFLAG CHAR(1),
  REQCLINICIANCLOSINGFLAG CHAR(1),
  OPSIMPELMENTATIONPHASE BIGINT,
  SEASONALFLAG CHAR(1),
  SEASONALSTARTDT TIMESTAMP(6),
  SEASONALENDDT TIMESTAMP(6),
  EFFECTIVESTARTDT TIMESTAMP(6),
  EFFECTIVEENDDT TIMESTAMP(6),
  RECORDINSERTDT TIMESTAMP(6),
  RECORDUPDTDT TIMESTAMP(6),
  INSERTEDBY VARCHAR(30),
  UPDTDBY VARCHAR(30),
  STANDARDRUNFLAG CHAR(1),
  INTERVENTIONFEEDBACKFAMILYID BIGINT,
  CONDITIONFEEDBACKFAMILYID BIGINT,
  ASHWELLNESSELIGIBILITYFLAG CHAR(1),
  HEALTHADVOCACYELIGIBILITYFLAG CHAR(1),
  CONSTRAINT RECOMMENDATIONS_PK PRIMARY KEY (RECOMMENDATIONSKEY)
 );

CREATE TABLE SQL_CE_RECOMMENDATIONTEXT(
  RECOMMENDATIONTEXTID BIGINT,
  RECOMMENDATIONID BIGINT,
  LANGUAGECD CHAR(2) ,
  RECOMMENDATIONTEXTTYPE VARCHAR(20) ,
  MESSAGETYPE CHAR(3) ,
  RECOMMENDATIONTITLE VARCHAR(200),
  RECOMMENDATIONTEXT VARCHAR(4000),
  RECORDINSERTDT TIMESTAMP(6),
  RECORDUPDATEDT TIMESTAMP(6),
  INSERTEDBY VARCHAR(30),
  UPDATEDBY VARCHAR(30),
  DEFAULTIN CHAR(1),
  CONSTRAINT RECOMMENDATIONTEXT_PK PRIMARY KEY (RECOMMENDATIONTEXTID)
);

CREATE TABLE SQL_CE_MEDICALFINDING(
  MEDICALFINDINGID BIGINT,
  MEDICALFINDINGTYPECD VARCHAR(12),
  MEDICALFINDINGNM VARCHAR(200),
  SEVERITYLEVELCD VARCHAR(12),
  IMPACTABLEFLG CHAR(1),
  CLINICAL_CONDITION_COD BIGINT,
  INSERTEDBY VARCHAR(30),
  RECORDINSERTDT TIMESTAMP (6),
  RECORDUPDTDT TIMESTAMP (6),
  UPDTDBY VARCHAR(30),
  ACTIVEFLG CHAR(1),
  OPPORTUNITYPOINTSDISCRCD VARCHAR(12),
  CONSTRAINT MEDICALFINDING_PK PRIMARY KEY (MEDICALFINDINGID)
) ;

CREATE TABLE SQL_CE_CLINICAL_CONDITION(
  CLINICAL_CONDITION_COD BIGINT,
  CLINICAL_CONDITION_NAM VARCHAR(200),
  INSERTED_BY VARCHAR(50),
  REC_INSERT_DATE DATE,
  REC_UPD_DATE DATE,
  UPDATED_BY VARCHAR(50),
  CLINICALCONDITIONCLASSCD VARCHAR(24),
  CLINICALCONDITIONTYPECD VARCHAR(12),
  CLINICALCONDITIONABBREV VARCHAR(50),
  CONSTRAINT CLINICAL_CONDITION_PK PRIMARY KEY (CLINICAL_CONDITION_COD)
);

CREATE TABLE SQL_CE_PRODUCTFINDING(
  PRODUCTFINDINGID BIGINT,
  PRODUCTFINDINGNM VARCHAR(100),
  SEVERITYLEVELCD VARCHAR(12),
  PRODUCTFINDINGTYPECD VARCHAR(12),
  PRODUCTMNEMONICCD VARCHAR(50),
  SUBPRODUCTMNEMONICCD VARCHAR(50),
  INSERTEDBY VARCHAR(30),
  RECORDINSERTDT TIMESTAMP(6),
  RECORDUPDTDT TIMESTAMP(6),
  UPDTDBY VARCHAR(30),
  CONSTRAINT PRODUCTFINDING_PK PRIMARY KEY (PRODUCTFINDINGID)
);

CREATE TABLE SQL_CE_DERIVEDFACTPRODUCTUSAGE(
  DERIVEDFACTPRODUCTUSAGEID BIGINT,
  DERIVEDFACTID BIGINT,
  PRODUCTMNEMONICCD VARCHAR(50),
  INSERTEDBY VARCHAR(30),
  RECORDINSERTDT TIMESTAMP(6),
  RECORDUPDTDT TIMESTAMP(6),
  UPDTDBY VARCHAR(30),
  CONSTRAINT DERIVEDFACTPRODUCTUSAGE_PK PRIMARY KEY (DERIVEDFACTPRODUCTUSAGEID)
);

CREATE TABLE SQL_CE_PRODUCTOPPORTUNITYPOINTS(
  OPPORTUNITYPOINTSDISCCD VARCHAR2(100),
  EFFECTIVESTARTDT VARCHAR(100),
  OPPORTUNITYPOINTSNBR BIGINT,
  EFFECTIVEENDDT TIMESTAMP(6),
  DERIVEDFACTPRODUCTUSAGEID BIGINT,
  INSERTEDBY VARCHAR2(30),
  RECORDINSERTDT TIMESTAMP(6),
  RECORDUPDTDT TIMESTAMP(6),
  UPDTDBY VARCHAR2(30),
  CONSTRAINT PRODUCTOPPORTUNITYPOINTS_PK PRIMARY KEY (OPPORTUNITYPOINTSDISCCD,EFFECTIVESTARTDT,OPPORTUNITYPOINTSNBR,DERIVEDFACTPRODUCTUSAGEID)
);

CREATE TABLE SQL_CE_OPPORTUNITYPOINTSDISCR(
  OPPORTUNITYPOINTSDISCRCD VARCHAR2(12),
  OPPORTUNITYPOINTSDISCNM VARCHAR2(255),
  INSERTEDBY VARCHAR2(30),
  RECORDINSERTDT TIMESTAMP(6),
  RECORDUPDTDT TIMESTAMP(6),
  UPDTDBY VARCHAR2(30),
  CONSTRAINT OPPORTUNITYPOINTSDISCR_PK PRIMARY KEY (OPPORTUNITYPOINTSDISCRCD)
);


