REATE TABLE "ODS"."ELEMENT"
   (	"ELEMENTID" NUMBER NOT NULL ENABLE,
	"ELEMENTCLASS" NUMBER NOT NULL ENABLE,
	"ELEMENTNM" VARCHAR2(50 BYTE),
	"COMMENTS" VARCHAR2(255 BYTE),
	"ELEMENTNUMBER" VARCHAR2(8 BYTE),
	"EFFECTIVESTARTDT" DATE,
	"EFFECTIVEENDDT" DATE,
	"RECORDINSERTDT" TIMESTAMP (6) DEFAULT systimestamp,
	"RECORDUPDTDT" TIMESTAMP (6) DEFAULT systimestamp,
	"INSERTEDBY" VARCHAR2(30 BYTE) DEFAULT USER,
	"UPDTDBY" VARCHAR2(30 BYTE) DEFAULT USER,
	"THERAPEUTICCLASS" VARCHAR2(4000 BYTE),
	"SENSITIVITYFLG" CHAR(1 BYTE),
	"DISPLAYTITLE" VARCHAR2(4000 BYTE),
	 PRIMARY KEY ("ELEMENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODS_REF_DATA"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 393216 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODS_REF_DATA" ;

   COMMENT ON COLUMN "ODS"."ELEMENT"."COMMENTS" IS 'A text or note associated with the given activity or definition';
   COMMENT ON COLUMN "ODS"."ELEMENT"."EFFECTIVESTARTDT" IS 'A date upon which the row was considered as active. This
date may be a date away from the date of insert/creation of the row.';
   COMMENT ON COLUMN "ODS"."ELEMENT"."EFFECTIVEENDDT" IS 'Date on which the row was rendered ineffective.  Usually the
value will remain null until then';
   COMMENT ON COLUMN "ODS"."ELEMENT"."RECORDINSERTDT" IS 'date and time at which the record was inserted.';
   COMMENT ON COLUMN "ODS"."ELEMENT"."RECORDUPDTDT" IS 'date and time at which the record was updated';
   COMMENT ON COLUMN "ODS"."ELEMENT"."INSERTEDBY" IS 'User Identifier used to Insert the row';
   COMMENT ON COLUMN "ODS"."ELEMENT"."UPDTDBY" IS 'User Identifier used to update the row';

  CREATE UNIQUE INDEX "ODS"."AKX1ELEMENT" ON "ODS"."ELEMENT" ("ELEMENTCLASS", "ELEMENTID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 131072 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODS_REF_DATA" ;

  CREATE UNIQUE INDEX "ODS"."XPKELEMENT" ON "ODS"."ELEMENT" ("ELEMENTID", "ELEMENTCLASS")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "ODS_REF_DATA" ;