
  CREATE TABLE CE.MEDICALFINDINGTYPE
   (	MEDICALFINDINGTYPECD VARCHAR2(12),
	MEDICALFINDINGTYPEDESC VARCHAR2(255),
	INSERTEDBY VARCHAR2(30) DEFAULT USER,
	RECORDINSERTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	RECORDUPDTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	UPDTDBY VARCHAR2(30) DEFAULT USER,
	HEALTHSTATEAPPLICABLEFLAG CHAR(1)
   ) ;
  ALTER TABLE CE.MEDICALFINDINGTYPE ADD CONSTRAINT MEDICALFINDINGTYPE_PK PRIMARY KEY (MEDICALFINDINGTYPECD)
  USING INDEX  ENABLE;


  CREATE TABLE CE.PRODUCTFINDINGTYPE
   (	PRODUCTFINDINGTYPECD VARCHAR2(12),
	PRODUCTFINDINGTYPEDESC VARCHAR2(255),
	INSERTEDBY VARCHAR2(30) DEFAULT USER,
	RECORDINSERTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	RECORDUPDTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	UPDTDBY VARCHAR2(30) DEFAULT USER
   ) ;


  CREATE TABLE CE.DERIVEDFACT
   (	DERIVEDFACTID NUMBER,
	DERIVEDFACTTRACKINGID NUMBER,
	DERIVEDFACTTYPEID NUMBER,
	INSERTEDBY VARCHAR2(30) DEFAULT USER,
	RECORDINSERTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	RECORDUPDTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	UPDTDBY VARCHAR2(30) DEFAULT USER
   ) ;
  ALTER TABLE CE.DERIVEDFACT ADD CONSTRAINT DERIVEDFACT_PK PRIMARY KEY (DERIVEDFACTID)
  USING INDEX  ENABLE;


  CREATE TABLE CE.RECOMMENDATION
   (	RECOMMENDATIONSKEY NUMBER NOT NULL ENABLE,
	RECOMMENDATIONID NUMBER(10,0) NOT NULL ENABLE,
	RECOMMENDATIONCODE VARCHAR2(200),
	RECOMMENDATIONDESC VARCHAR2(4000),
	RECOMMENDATIONTYPE VARCHAR2(20) NOT NULL ENABLE,
	CCTYPE VARCHAR2(50),
	CLINICALREVIEWTYPE VARCHAR2(20) NOT NULL ENABLE,
	AGERANGEID NUMBER,
	ACTIONCODE VARCHAR2(200),
	THERAPEUTICCLASS VARCHAR2(300),
	MDCCODE VARCHAR2(20),
	MCCCODE VARCHAR2(50),
	PRIVACYCATEGORY VARCHAR2(20) NOT NULL ENABLE,
	INTERVENTION VARCHAR2(200),
	RECOMMENDATIONFAMILYID NUMBER,
	RECOMMENDPRECEDENCEGROUPID NUMBER,
	INBOUNDCOMMUNICATIONROUTE VARCHAR2(15),
	SEVERITY VARCHAR2(2),
	PRIMARYDIAGNOSIS VARCHAR2(300),
	SECONDARYDIAGNOSIS VARCHAR2(300),
	ADVERSEEVENT VARCHAR2(300),
	ICMCONDITIONID NUMBER,
	WELLNESSFLAG CHAR(1),
	VBFELIGIBLEFLAG CHAR(1),
	COMMUNICATIONRANKING NUMBER,
	PRECEDENCERANKING NUMBER,
	PATIENTDERIVEDFLAG CHAR(1),
	LABREQUIREDFLAG CHAR(1),
	UTILIZATIONTEXTAVAILABLEF CHAR(1),
	SENSITIVEMESSAGEFLAG CHAR(1),
	HIGHIMPACTFLAG CHAR(1),
	ICMLETTERFLAG CHAR(1),
	REQCLINICIANCLOSINGFLAG CHAR(1),
	OPSIMPELMENTATIONPHASE NUMBER,
	SEASONALFLAG CHAR(1),
	SEASONALSTARTDT DATE,
	SEASONALENDDT DATE,
	EFFECTIVESTARTDT DATE NOT NULL ENABLE,
	EFFECTIVEENDDT DATE,
	RECORDINSERTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	RECORDUPDTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	INSERTEDBY VARCHAR2(30) DEFAULT USER,
	UPDTDBY VARCHAR2(30) DEFAULT USER,
	STANDARDRUNFLAG CHAR(1),
	INTERVENTIONFEEDBACKFAMILYID NUMBER,
	CONDITIONFEEDBACKFAMILYID NUMBER,
	ASHWELLNESSELIGIBILITYFLAG CHAR(1),
	HEALTHADVOCACYELIGIBILITYFLAG CHAR(1)
   ) ;
 

  CREATE TABLE CE.RECOMMENDATIONTEXT
   (	RECOMMENDATIONTEXTID NUMBER NOT NULL ENABLE,
	RECOMMENDATIONID NUMBER(10,0) NOT NULL ENABLE,
	LANGUAGECD CHAR(2) NOT NULL ENABLE,
	RECOMMENDATIONTEXTTYPE VARCHAR2(20) NOT NULL ENABLE,
	MESSAGETYPE CHAR(3) NOT NULL ENABLE,
	RECOMMENDATIONTITLE VARCHAR2(200),
	RECOMMENDATIONTEXT VARCHAR2(4000),
	RECORDINSERTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	RECORDUPDATEDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	INSERTEDBY VARCHAR2(30) DEFAULT USER,
	UPDATEDBY VARCHAR2(30) DEFAULT USER,
	DEFAULTIN CHAR(1)
   ) ;
  

  CREATE TABLE CE.MEDICALFINDING
   (	MEDICALFINDINGID NUMBER,
	MEDICALFINDINGTYPECD VARCHAR2(12),
	MEDICALFINDINGNM VARCHAR2(200),
	SEVERITYLEVELCD VARCHAR2(12),
	IMPACTABLEFLG CHAR(1) DEFAULT 'N',
	CLINICAL_CONDITION_COD NUMBER,
	INSERTEDBY VARCHAR2(30) DEFAULT USER,
	RECORDINSERTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	RECORDUPDTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	UPDTDBY VARCHAR2(30) DEFAULT USER,
	ACTIVEFLG CHAR(1),
	OPPORTUNITYPOINTSDISCRCD VARCHAR2(12)
   ) ;


  CREATE TABLE CE.CLINICAL_CONDITION
   (	CLINICAL_CONDITION_COD NUMBER,
	CLINICAL_CONDITION_NAM VARCHAR2(200),
	INSERTED_BY VARCHAR2(50),
	REC_INSERT_DATE DATE,
	REC_UPD_DATE DATE,
	UPDATED_BY VARCHAR2(50),
	CLINICALCONDITIONCLASSCD NUMBER,
	CLINICALCONDITIONTYPECD VARCHAR2(12),
	CLINICALCONDITIONABBREV VARCHAR2(50)
   ) ;
  ALTER TABLE CE.CLINICAL_CONDITION ADD CONSTRAINT CLINICAL_CONDITION_PK PRIMARY KEY (CLINICAL_CONDITION_COD)
  USING INDEX  ENABLE;


  CREATE TABLE CE.PRODUCTFINDING
   (	PRODUCTFINDINGID NUMBER,
	PRODUCTFINDINGNM VARCHAR2(100),
	SEVERITYLEVELCD VARCHAR2(12),
	PRODUCTFINDINGTYPECD VARCHAR2(12),
	PRODUCTMNEMONICCD VARCHAR2(50),
	SUBPRODUCTMNEMONICCD VARCHAR2(50),
	INSERTEDBY VARCHAR2(30) DEFAULT USER,
	RECORDINSERTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	RECORDUPDTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	UPDTDBY VARCHAR2(30) DEFAULT USER
   ) ;


  CREATE TABLE CE.DERIVEDFACTPRODUCTUSAGE
   (	DERIVEDFACTPRODUCTUSAGEID NUMBER,
	DERIVEDFACTID NUMBER,
	PRODUCTMNEMONICCD VARCHAR2(50),
	INSERTEDBY VARCHAR2(30) DEFAULT USER,
	RECORDINSERTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	RECORDUPDTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	UPDTDBY VARCHAR2(30) DEFAULT USER
   ) ;
  ALTER TABLE CE.DERIVEDFACTPRODUCTUSAGE ADD CONSTRAINT DERIVEDFACTPRODUCTUSAGE_PK PRIMARY KEY (DERIVEDFACTPRODUCTUSAGEID)
  USING INDEX  ENABLE;


  CREATE TABLE CE.PRODUCTOPPORTUNITYPOINTS
   (	OPPORTUNITYPOINTSDISCCD VARCHAR2(100),
	EFFECTIVESTARTDT DATE,
	OPPORTUNITYPOINTSNBR NUMBER,
	EFFECTIVEENDDT DATE,
	DERIVEDFACTPRODUCTUSAGEID NUMBER,
	INSERTEDBY VARCHAR2(30) DEFAULT USER,
	RECORDINSERTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	RECORDUPDTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	UPDTDBY VARCHAR2(30) DEFAULT USER
   ) ;


  CREATE TABLE CE.OPPORTUNITYPOINTSDISCR
   (	OPPORTUNITYPOINTSDISCRCD VARCHAR2(12),
	OPPORTUNITYPOINTSDISCNM VARCHAR2(255),
	INSERTEDBY VARCHAR2(30) DEFAULT USER,
	RECORDINSERTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	RECORDUPDTDT TIMESTAMP (6) DEFAULT SYSTIMESTAMP,
	UPDTDBY VARCHAR2(30) DEFAULT USER
   ) ;
  ALTER TABLE CE.OPPORTUNITYPOINTSDISCR ADD CONSTRAINT OPPORTUNITYPOINTSDISCR_PK PRIMARY KEY (OPPORTUNITYPOINTSDISCRCD)
  USING INDEX  ENABLE;
